compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  midnight-ntwrk:
    npmRegistryServer: "https://registry.yarnpkg.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs

yarnPath: .yarn/releases/yarn-4.1.0.cjs
